### PR TITLE
feat: ilorin date fix

### PR DESCRIPTION
**Pull request by PrimeFord**
how is this boss.... testing

### CODE REVIEW

**Comment by kaf-lamed-beyt** [comment]
Ayy! @PrimeFord Congrats on your first PR to this repo. 🚀

But... I think there's a merge conflict, so i won't be able to merge it, for now, at least. To be honest, it is nothing to worry about. 

Screenshot_20230713_213147_Chrome

What it means is that, the change you made doesn't match the latest content of the README file. 

So, here's how you might resolve it. 

- open the project and try doing 👇🏼 
```bash 
git pull upstream master
``` 
The command above assumes that you've set this repo as an upstream. 

When you do this, it'll fetch the latest change from this repo, and you'd encounter some weird syntaxes that are similar to the one below 

```md
>>>>>>>>>random number761qhwvwkoqra11tvx
``` 

I think the last change is [chore: remove trailing spaces](https://github.com/kaf-lamed-beyt/ng-tech-events/commit/449783d7319d28bc5e230c728210498b3f20ade8) or so.

Try comparing both of them together.

Or better still... just copy the content of the README file and add the change you worked on, previously. 

Let me know if this helps. 🤲🏽

**Review by Petsamuel — CHANGES_REQUESTED** [review]
review: @PrimeFord this is the old version of the code.
issue:#45  wasn't in your codebase.

Suggestion: Kindly Fech the latest version of the code and make your changes

**Comment by PrimeFord** [comment]
> Ayy! @PrimeFord Congrats on your first PR to this repo. 🚀
> 
> But... I think there's a merge conflict, so i won't be able to merge it, for now, at least. To be honest, it is nothing to worry about.
> 
> Screenshot_20230713_213147_Chrome
> 
> What it means is that, the change you made doesn't match the latest content of the README file.
> 
> So, here's how you might resolve it.
> 
> * open the project and try doing 👇🏼
> 
> ```shell
> git pull upstream master
> ```
> 
> The command above assumes that you've set this repo as an upstream.
> 
> When you do this, it'll fetch the latest change from this repo, and you'd encounter some weird syntaxes that are similar to the one below
> 
> ```
> >>>>>>>>>random number761qhwvwkoqra11tvx
> ```
> 
> I think the last change is [chore: remove trailing spaces](https://github.com/kaf-lamed-beyt/ng-tech-events/commit/449783d7319d28bc5e230c728210498b3f20ade8) or so.
> 
> Try comparing both of them together.
> 
> Or better still... just copy the content of the README file and add the change you worked on, previously.
> 
> Let me know if this helps. 🤲🏽

yes it was

**Comment by PrimeFord** [comment]
> Ayy! @PrimeFord Congrats on your first PR to this repo. 🚀
> 
> But... I think there's a merge conflict, so i won't be able to merge it, for now, at least. To be honest, it is nothing to worry about.
> 
> Screenshot_20230713_213147_Chrome
> 
> What it means is that, the change you made doesn't match the latest content of the README file.
> 
> So, here's how you might resolve it.
> 
> * open the project and try doing 👇🏼
> 
> ```shell
> git pull upstream master
> ```
> 
> The command above assumes that you've set this repo as an upstream.
> 
> When you do this, it'll fetch the latest change from this repo, and you'd encounter some weird syntaxes that are similar to the one below
> 
> ```
> >>>>>>>>>random number761qhwvwkoqra11tvx
> ```
> 
> I think the last change is [chore: remove trailing spaces](https://github.com/kaf-lamed-beyt/ng-tech-events/commit/449783d7319d28bc5e230c728210498b3f20ade8) or so.
> 
> Try comparing both of them together.
> 
> Or better still... just copy the content of the README file and add the change you worked on, previously.
> 
> Let me know if this helps. 🤲🏽

yes it was helpful boss thanks!!! sorry i was being a handfull

**Comment by PrimeFord** [comment]
> Review: @PrimeFord this is the old version of the code. Issue: #45 wasn't in your codebase.
> 
> Suggestion: Kindly Fetch the latest version of the code and make your changes

thanks sam you've been really helpful

**Pull request closed without merging**
