### PR TITLE
Refactor: created a new module for uniquecategories

### PR DESCRIPTION
**Pull request by Tonie-NG**
Fixes issue #63

### CODE REVIEW

**Comment by kaf-lamed-beyt** [comment]
Thanks for opening this! I should be back with feedbacks by tomorrow after a review. No light for now 🤲🏽

**Comment by Tonie-NG** [comment]
Hello @kaf-lamed-beyt . What's the update on this?

**Comment by kaf-lamed-beyt** [comment]
Hi @Tonie-NG,

Apologies for the delay. I haven't been able to do anything tangible since I last commented here. 

But, one thing I did was to take a look at the deploy preview and I noticed that the categories list isn't rendered in the UI. 

Screenshot_20230724_180751_Chrome

One step towards fixing this would be to identify why it is not being rendered. Perhaps you're not importing/using the `uniqueCategories` array properly.

**Comment by Tonie-NG** [comment]
Alright boss, I'll look at it and send a feedback by tomorrow. Thank you

**Comment by Tonie-NG** [comment]
I'll work on this afresh on another branch. Thanks

**Pull request closed without merging**
