### PR TITLE
feat: Events Update

### PR DESCRIPTION
**Pull request by PrimeFord**
done... i reForked the whole respo

### CODE REVIEW

**Comment by kaf-lamed-beyt** [comment]
Awesome!! 

So have you added the new events? Cybersecurity and the ethereum meetup?

**Comment by PrimeFord** [comment]
> 

yes boss

**Comment by PrimeFord** [comment]
> > 
> 
> yes boss

looks like im having issue deployig the changes

**Comment by kaf-lamed-beyt** [comment]
> > > 
> > 
> > 
> > yes boss
> 
> looks like im having issue deployig the changes

Don't worry about that. So long as you have added the events. We can merge it. I'll go over what the cause of the deploy error is, later on.

**Review by kaf-lamed-beyt — APPROVED** [review]
You Rock! @PrimeFord 🚀

**Pull request merged**
