### PR TITLE
update: Readme.md

### PR DESCRIPTION
**Pull request by Petsamuel**
added the Ibadan event

### CODE REVIEW

**Comment by kaf-lamed-beyt** [comment]
The recent PRs have caused this one to have conflicts that must be resolved. I'll co-author some commit with you now. So, whenever you get this, kindy provide the link to the event.

**Comment by Petsamuel** [comment]
Noted

**Comment by Petsamuel** [comment]
No link for that.

**Comment by kaf-lamed-beyt** [comment]
Oh okay. 🚀

**Comment by kaf-lamed-beyt** [comment]
@Petsamuel, when you're chanced, there are some issues that you can work on, if you want.

**Pull request merged**
